Loading python/3.7.11-base
  ERROR: Module cannot be loaded due to a conflict.
    HINT: Might try "module unload python" first.
Loading openmpi/3.1.6-gcc11
  ERROR: Module cannot be loaded due to a conflict.
    HINT: Might try "module unload openmpi" first.
rm: cannot remove 'cp2k.out': No such file or directory
--------------------------------------------------------------------------
ORTE has lost communication with a remote daemon.

  HNP daemon   : [[58753,0],0] on node i04r01c01s11
  Remote daemon: [[58753,0],1] on node i04r01c02s01

This is usually due to either a failure of the TCP network
connection to the node, or possibly an internal failure of
the daemon itself. We cannot recover from this failure, and
therefore will terminate the job.
--------------------------------------------------------------------------
slurmstepd: error: *** JOB 4849431 ON i04r01c01s11 CANCELLED AT 2025-08-06T07:42:37 DUE TO TIME LIMIT ***
